version: "3.8"
services:
  etcd:
    image: "quay.io/coreos/etcd"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001
